---

- name: Ensure aur directory exists for user
  become: yes
  become_user: {{ user }}
  file:
    path: /home/{{ user }}/aur
    state: directory

- name: Clone yay AUR helper
  become: yes
  become_user: {{ user }}
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: /home/{{ user }}/aur/yay

- name: Install yay
  become: yes
  become_user: {{ user }}
  command: makepkg --noconfirm -si
  args:
    chdir: /home/{{ user }}/aur/yay
