---

- name: Ensure oh-my-zsh directory exists for user
  become: yes
  become_user: "{{ user }}"
  file:
    path: "/home/{{ user }}/git/packages/expand-disk"
    state: directory

- name: Copy extend_partition.sh script
  copy:
    src: extend_partition.sh
    dest: "/home/{{ user }}/git/packages/expand-disk/extend_partition.sh"
    owner: root
    group: root
    mode: '0755'
  register: extended_partition_script

- name: Resize root partition
  become: yes
  shell: "/home/{{ user }}/git/packages/expand-disk/extend_partition.sh"
  when: extended_partition_script.changed
