---

- name: Run distro specific base tasks
  include_tasks: "{{ loop_expand_disk_tasks }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_release | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  loop_control:
    loop_var: loop_expand_disk_tasks

- name: Ensure expand-disk directory exists for user
  become: yes
  become_user: "{{ user }}"
  file:
    path: "/home/{{ user }}/git/packages/expand-disk"
    state: directory

- name: Copy extend_partition.sh script
  copy:
    src: extend_partition.sh
    dest: "/home/{{ user }}/git/packages/expand-disk/extend_partition.sh"
    owner: root
    group: root
    mode: '0755'
  register: extended_partition_script

- name: Resize root partition
  become: yes
  shell: "/home/{{ user }}/git/packages/expand-disk/extend_partition.sh"
  when: extended_partition_script.changed
