---

- name: Run distro specific base tasks
  include_tasks: "{{ loop_shell_tasks }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_release | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  loop_control:
    loop_var: loop_shell_tasks

- name: Set default shell to zsh for {{ user }} user
  command: "chsh -s /bin/zsh {{ user }}"
  changed_when: False

- name: Check if oh-my-zsh is already installed
  stat:
    path: "/home/{{ user }}/.oh-my-zsh"
  register: ohmyzsh_installed

- name: Install oh-my-zsh
  include_tasks: ohmyzsh.yml
  when: not ohmyzsh_installed.stat.exists

- name: Install nerd fonts
  include_tasks: nerdfonts.yml

- name: Ensures go dir exists
  file:
    path: "/home/{{ user }}/go"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"

- name: Install spaceship prompt
  include_tasks: spaceship.yml
