---

- name: Ensure aur directory exists for user
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ aur_location }}"
    state: directory

- name: Clone smbmap AUR repo
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "{{ smbmap_package_repo }}"
    dest: "{{ aur_location }}/smbmap"
  register: smbmap_clone

- name: Install smbmap
  become: yes
  become_user: "{{ user }}"
  command: makepkg --noconfirm -si
  args:
    chdir: "{{ aur_location }}/smbmap"
  when: smbmap_clone.changed
