---

- name: Ensure aur directory exists for user
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ aur_location }}"
    state: directory

- name: Clone google-chrome repo
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "{{ chrome_package_repo }}"
    dest: "{{ aur_location }}/google-chrome"
  register: googlechrome_clone

- name: Install google-chrome
  become: yes
  become_user: "{{ user }}"
  command: makepkg --noconfirm -si
  args:
    chdir: "{{ aur_location }}/google-chrome"
  when: googlechrome_clone.changed
