---

- hosts: all
  become: yes

  pre_tasks:
    - name: Update system
      pacman:
        update_cache: yes
        upgrade: yes

  roles:
    - expand-disk
    - base
    - locale # thank you John! :D
    - iptables
    - shell
    - asdf
    - terraform
    - dotfiles
    - xorg
    - i3 # can replace with gnome
    - yay
    - golang
    - nasm
    - gdb
    - aflplusplus
    - crashwalk
    - honggfuzz
    - firefox
    - google-chrome
    - intellij
    - vscode
    - docker
    - openssh
    - openvpn
    - nmap
    - sslscan
    - wireshark
    - proxychains
    - smbclient
    - filezilla
    - burpsuite
    - ghidra
    - radare
    - cutter
    - seclists
