---

- name: Ensure packages directory exists for user
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ download_location }}"
    state: directory

- name: Clone SecLists repo
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "{{ seclists_package_repo }}"
    dest: "{{ download_location }}/seclists"
    depth: "1"
