---

- name: Ensure packages directory exists for user
  become: yes
  become_user: {{ user }}
  file:
    path: /home/{{ user }}/git/packages
    state: directory

- name: Clone SecLists repo
  become: yes
  become_user: {{ user }}
  git:
    repo: https://github.com/danielmiessler/SecLists.git
    dest: /home/{{ user }}/git/packages/seclists
    depth: 1
