---

- name: Ensure aur directory exists for user
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ aur_location }}"
    state: directory

- name: Clone smtp-user-enum AUR repo
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "{{ package_repo }}"
    dest: "{{ aur_location }}/smtp-user-enum"
  register: smtpuserenum_clone

- name: Install smtp-user-enum
  become: yes
  become_user: "{{ user }}"
  command: makepkg --noconfirm -si
  args:
    chdir: "{{ aur_location }}/smtp-user-enum"
  when: smtpuserenum_clone.changed
