---

docker_group: docker
docker_service: docker.service

docker__apt_ignore_key_error: true

docker__channel: "stable"

docker__old_pkgs:
  - "docker"
  - "docker-engine"
  - "docker.io"
  - "containerd"
  - "runc"

docker__pkg_dependencies:
  - "apt-transport-https"
  - "ca-certificates"
  - "curl"
  - "cron"
  - "gnupg-agent"
  - "software-properties-common"

docker__apt_gpg_id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88"

docker__apt_key_server: "https://download.docker.com/linux/ubuntu/gpg"

docker__apt_repo_info: >
  deb [arch=amd64]
  https://download.docker.com/linux/ubuntu
  focal {{ docker__channel }}

docker__package:
  - "docker-ce"
  - "docker-ce-cli"
  - "containerd.io"

docker__compose_version: "1.28.2"

docker__compose_url: "https://github.com/docker/compose/releases/download/{{ docker__compose_version }}/docker-compose-Linux-x86_64"

docker__compose_dest_file: "/usr/local/bin/docker-compose"
