---

- name: Ensure packages directory exists for user
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ download_location }}"
    state: directory

- name: clone asdf from github
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "{{ download_location }}/asdf"
    depth: "1"
  register: asdf_clone

- name: Create symbolic link to asdf
  file:
    src: "{{ download_location }}/asdf"
    dest: "/home/{{ user }}/.asdf"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
