---

- name: Ensure packages directory exists for user
  become: yes
  become_user: "{{ user }}"
  file:
    path: "/home/{{ user }}/git/packages"
    state: directory

- name: clone asdf from github
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: "/home/{{ user }}/git/packages/asdf"
    depth: 1
  register: asdf_clone

- name: Create symbolic link to asdf
  file:
    src: "/home/{{ user }}/git/packages/asdf"
    dest: "/home/{{ user }}/.asdf"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link

- name: Install Terraform addon for asdf
  become: yes
  become_user: "{{ user }}"
  command: "/home/{{ user }}/.asdf/bin/asdf plugin-add terraform https://github.com/Banno/asdf-hashicorp.git"
  when: (terraform_version is defined) and (terraform_version|length > 0) and (asdf_clone.changed)
  ignore_errors: yes


- name: Install Terraform with asdf
  become: yes
  become_user: "{{ user }}"
  command: /home/{{ user }}/.asdf/bin/asdf install terraform {{ terraform_version }}
  when: (terraform_version is defined) and (terraform_version|length > 0) and (asdf_clone.changed)
  ignore_errors: yes
