---

- name: Ensure aur directory exists for user
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ aur_location }}"
    state: directory

- name: Clone burpsuite AUR repo
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://aur.archlinux.org/burpsuite.git
    dest: "{{ aur_location }}/burpsuite"
  register: burpsuite_clone

- name: Install burpsuite
  become: yes
  become_user: "{{ user }}"
  command: makepkg --noconfirm -si
  args:
    chdir: "{{ aur_location }}/burpsuite"
  when: burpsuite_clone.changed
