---

- name: Install Display Manager
  pacman:
    name:
      - lightdm
      - lightdm-gtk-greeter
    state: present

- name: Install i3
  pacman:
    name:
      - i3-gaps
      - i3status
      - i3lock
    state: present

- name: Install Fonts
  pacman:
    name:
      - noto-fonts
      - ttf-ubuntu-font-family
      - ttf-dejavu
      - ttf-freefont
      - ttf-liberation
      - ttf-droid
      - ttf-inconsolata
      - ttf-roboto
      - terminus-font
      - ttf-font-awesome
    state: present

- name: Install Arc Theme
  pacman:
    name:
      - arc-gtk-theme
      - gtk-engine-murrine
      - gnome-themes-extra
    state: present

- name: Install utilities
  pacman:
    name:
      - alacritty
      - rxvt-unicode
      - xsel
      - rofi
      - conky
      - dmenu
      - urxvt-perls
      - perl-anyevent-i3
      - perl-json-xs
      - xsettingsd
      - lxappearance
      - feh
      - xclip
      - thunar
      - gvfs
      - thunar-volman
      - scrot
      - screenfetch
