---

- name: Ensure aur directory exists for user
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ aur_location }}"
    state: directory

- name: Clone ffuf AUR repo
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "{{ package_repo }}"
    dest: "{{ aur_location }}/ffuf"
  register: ffuf_clone

- name: Install ffuf
  become: yes
  become_user: "{{ user }}"
  command: makepkg --noconfirm -si
  args:
    chdir: "{{ aur_location }}/ffuf"
  when: ffuf_clone.changed
