---

- name: Run distro specific base tasks
  include_tasks: "{{ loop_docker_tasks }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_release | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  loop_control:
    loop_var: loop_docker_tasks

- name: Copy GDM config file to use Xorg
  copy:
    src: custom.conf
    dest: /etc/gdm/custom.conf
    owner: root
    group: root
    mode: '0644'

- name: Enable GDM
  systemd:
    name: gdm
    enabled: yes

- name: Enable NetworkManager
  systemd:
    name: NetworkManager
    enabled: yes

- name: Configure Gnome to use the X keyboard layout by default
  command: gsettings set org.gnome.desktop.input-sources sources '[]'

- include: theme.yml
  become: yes
  become_user: {{ user }}
