---

- name: Ensure aur directory exists for user
  become: yes
  become_user: "{{ user }}"
  file:
    path: "/home/{{ user }}/aur"
    state: directory

- name: Clone onesixtyone AUR repo
  become: yes
  become_user: "{{ user }}"
  git:
    repo: https://aur.archlinux.org/onesixtyone-git.git
    dest: "/home/{{ user }}/aur/onesixtyone"
  register: onesixtyone_clone

- name: Install onesixtyone
  become: yes
  become_user: "{{ user }}"
  command: makepkg --noconfirm -si
  args:
    chdir: "/home/{{ user }}/aur/onesixtyone"
  when: onesixtyone_clone.changed
