---

- name: Add cilium network plugin helm repo
  community.kubernetes.helm_repository:
    name: cilium
    repo_url: "https://helm.cilium.io/"

- name: Deploy Cilium K8s CNI
  community.kubernetes.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    values:
      containerRuntime:
        integration: "containerd"
        socketPath: "/var/run/k3s/containerd/containerd.sock"
      kubeProxyReplacement: "strict"
      hubble:
        enabled: "true"
        listenAddress: ":4244"
        metrics:
          enabled:
          - dns
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        relay:
          enabled: "true"
        ui:
          enabled: "true"
          ingress:
            enabled: true
            hosts:
            - "{{ hubble_host }}"
      ipam:
        mode: "kubernetes"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
