---

- name: Dependency - python 3 pip
  apt:
    name: "python3-pip"
    state: present

- name: Dependency - Helm - Retrieve helm binary archive.
  unarchive:
    src: "https://get.helm.sh/helm-{{ helm_version }}-linux-amd64.tar.gz"
    dest: /tmp
    creates: /usr/local/bin/helm
    remote_src: yes

- name: Dependency - Helm - Move helm binary into place.
  command: cp /tmp/linux-amd64/helm /usr/local/bin/helm
  args:
    creates: /usr/local/bin/helm

- name: Dependency - python pylint
  pip:
    name: pylint

- name: Dependency - python openshift
  pip:
    name: openshift
