---

- name: Ensure role dependencies are installed
  include_tasks: dependencies.yml

- name: Download k3s install script
  get_url:
    url: https://get.k3s.io
    dest: /opt/k3s_install.sh
    mode: '0754'
    owner: root
    group: root
  register: installer_dl

- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  command: swapoff -a
  when: installer_dl is changed
  changed_when: False

- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'
  when: installer_dl is changed

- name: Install & Upgrade k3s
  command: /opt/k3s_install.sh
  environment:
    INSTALL_K3S_EXEC: "--flannel-backend=none --no-flannel"
    INSTALL_K3S_VERSION: "{{ k3s_version }}"
  when: installer_dl is changed

- name: retrieve k3s kubeconfig
  fetch:
    src: "/etc/rancher/k3s/k3s.yaml"
    dest: "module_utils/kube/kubeconfig-{{ inventory_hostname }}"
    flat: yes
  when: installer_dl is changed

- name: fix kubeconfig
  replace:
    path: "{{ playbook_dir }}/module_utils/kube/kubeconfig-{{ inventory_hostname }}"
    regexp: "127.0.0.1"
    replace: "{{ ansible_default_ipv4.address }}"
  delegate_to: localhost
  when: installer_dl is changed

- name: Ensure bpffs is mount (required by Cilium)
  mount:
    src: bpffs
    path: /sys/fs/bpf
    fstype: bpf
    opts: defaults
    dump: "0"
    passno: "0"
    state: mounted

- name: Add cilium network plugin helm repo
  community.kubernetes.helm_repository:
    name: cilium
    repo_url: "https://helm.cilium.io/"

- name: Deploy Cilium K8s CNI
  community.kubernetes.helm:
    name: cilium
    chart_ref: cilium/cilium
    release_namespace: kube-system
    values:
      containerRuntime:
        integration: "containerd"
        socketPath: "/var/run/k3s/containerd/containerd.sock"
      kubeProxyReplacement: "strict"
      hubble:
        enabled: "true"
        listenAddress: ":4244"
        metrics:
          enabled:
          - dns
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
        relay:
          enabled: "true"
        ui:
          enabled: "true"
          ingress:
            enabled: true
            hosts:
            - "{{ hubble_host }}"
      ipam:
        mode: "kubernetes"
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml

# - name: Create ambassador k8s namespace
#   community.kubernetes.k8s:
#     name: ambassador
#     api_version: v1
#     kind: Namespace
#     state: present
#   environment:
#     KUBECONFIG: /etc/rancher/k3s/k3s.yaml

# - name: Add Ambassador helm repo
#   community.kubernetes.helm_repository:
#     name: datawire
#     repo_url: "https://www.getambassador.io"

# - name: Deploy Cilium K8s CNI
#   community.kubernetes.helm:
#     name: ambassador
#     chart_ref: datawire/ambassador
#     release_namespace: ambassador
#   environment:
#     KUBECONFIG: /etc/rancher/k3s/k3s.yaml
