---

- name: Ensure aur directory exists for user
  become: yes
  become_user: "{{ user }}"
  file:
    path: "{{ aur_location }}"
    state: directory

- name: Clone sipvicious AUR repo
  become: yes
  become_user: "{{ user }}"
  git:
    repo: "{{ package_repo }}"
    dest: "{{ aur_location }}/sipvicious"
  register: sipvicious_clone

- name: Install sipvicious
  become: yes
  become_user: "{{ user }}"
  command: makepkg --noconfirm -si
  args:
    chdir: "{{ aur_location }}/sipvicious"
  when: sipvicious_clone.changed
