---

- name: Ensure aur directory exists for user
  become: yes
  become_user: {{ user }}
  file:
    path: /home/{{ user }}/aur
    state: directory

- name: Clone sipvicious AUR repo
  become: yes
  become_user: {{ user }}
  git:
    repo: https://aur.archlinux.org/sipvicious.git
    dest: /home/{{ user }}/aur/sipvicious

- name: Install sipvicious
  become: yes
  become_user: {{ user }}
  command: makepkg --noconfirm -si
  args:
    chdir: /home/{{ user }}/aur/sipvicious
